apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cswzdck4v-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cswzdck4v-java-springboot-gitops